### ISSUE TITLE
Impement auto-network notarization of hashes

### ISSUE THREAD

**Issue by n8fr8** [guardianproject/proofmode#8]
Investigate blockchain based and other solutions.

Stampery
OpenTimestamps: https://petertodd.org//2016/opentimestamps-announcement

**Comment by petertodd** [comment]
Awesome!

I guess proofmode is written in 100% java? There's a [Javascript OpenTimestamps library](https://github.com/opentimestamps/javascript-opentimestamps), but no-one has written a Java one yet. The client-side part of the OpenTimestamps protocol is pretty simple though, so creating one shouldn't be too hard.

**Comment by petertodd** [comment]
BTW we have a Java library now: https://github.com/opentimestamps/java-opentimestamps

I'm not a Java dev, so I don't know much about it, but if you have any questions I can certainly help get you in touch with the devs behind it.

**Comment by petertodd** [comment]
Oh, and seems this repo is a bit more up-to-date: https://github.com/eternitywall/java-opentimestamps

**Comment by petertodd** [comment]
I noticed that this is in fact implemented! IIUC you're timestamping the photo hash; I'd suggest you instead timestamp the PGP signatures. This is better because it:

1. Allows the PGP signatures to be verified even if the secret key is compromised, by proving that the signature was created prior to the compromise.
2. Prevents the photo metadata from being modified after the fact.
3. Can be implemented as a standard `.ots` file, allowing users to easily verify the proof with standard OTS tooling (I see you're also using another notary service in parallel; maybe there's an equivalent standard file format for it too? That additional notary can also be added to OTS directly).

In any case, it's really cool to see this get implemented! I'm happy to answer any other questions you have.

**Comment by n8fr8** [comment]
Just to loop back on this, that we are indeed using OTS files now, which works great.

May still consider what we are actually notarizing, but for now we are pretty happy between this working in combination with the PGP signatures and other notary services.
